app = "perplexity-completions-mcp-private"
primary_region = "sjc"

[build]
dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"
PORT = "8080"

# If you're on Machines/v2, prefer http_service (recommended):
[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines = true         # <— additional machines stop after inactivity
min_machines_running = 1          # <— keep primary machine always on
processes = ["app"]

  [http_service.concurrency]
  type = "requests"
  soft_limit = 50
  hard_limit = 100

  [[http_service.checks]]
  port = 8080
  type = "http"
  method = "GET"
  path = "/health"
  interval = "10s"
  timeout = "5s"
  grace_period = "30s"

# VM sizing
[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"
