# fly.toml app configuration file generated for perplexity-completions-mcp-private on 2025-10-02
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'perplexity-completions-mcp-private'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
